export const USER_ROLES = {
  ORGANIZER: 'ORGANIZER',
  VOLUNTEER: 'VOLUNTEER'
};

export const EVENT_STATUSES = {
  PLANNING: 'PLANNING',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

export const TASK_STATUSES = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  BLOCKED: 'BLOCKED'
};

export const TASK_PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

export const TASK_CATEGORIES = [
  'Venue',
  'Registration',
  'Sponsorship',
  'Marketing',
  'Technical',
  'Hospitality',
  'Finance',
  'Logistics',
  'Design',
  'Documentation'
];

export const TASK_SOURCES = {
  MANUAL: 'MANUAL',
  AI_PLANNER: 'AI_PLANNER',
  MEETING_AI: 'MEETING_AI',
  AI_ACTION: 'AI_ACTION'
};

export const RISK_SEVERITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

export const RISK_STATUSES = {
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  IGNORED: 'IGNORED'
};

export const RISK_SOURCES = {
  RULE_ENGINE: 'RULE_ENGINE',
  AI_ANALYSIS: 'AI_ANALYSIS',
  MANUAL: 'MANUAL'
};

export const AI_ACTION_TYPES = {
  CREATE_TASK: 'CREATE_TASK',
  ASSIGN_TASK: 'ASSIGN_TASK',
  UPDATE_TASK_STATUS: 'UPDATE_TASK_STATUS',
  CREATE_RISK: 'CREATE_RISK',
  SEND_NOTIFICATION: 'SEND_NOTIFICATION',
  BATCH_ASSIGN: 'BATCH_ASSIGN'
};

export const AI_ACTION_STATUSES = {
  PROPOSED: 'PROPOSED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXECUTED: 'EXECUTED',
  FAILED: 'FAILED'
};

export const NOTIFICATION_TYPES = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  DEADLINE_ALERT: 'DEADLINE_ALERT',
  RISK_DETECTED: 'RISK_DETECTED',
  ACTION_EXECUTED: 'ACTION_EXECUTED',
  ANNOUNCEMENT: 'ANNOUNCEMENT'
};
